export const DELETE_ITEM = 'DELETE_ITEM';
export const SVUOTA_CARRELLO = 'SVUOTA_CARRELLO';
export const LOADING_DATA = 'LOADING_DATA';
export const AUMENTA_QTY = 'AUMENTA_QTY';
export const DIMINUISCI_QTY = 'DIMINUISCI_QTY';
export const COSTO_TOTALE = 'COSTO_TOTALE';
export const CONTATORE = "CONTATORE";
